package dao;

import java.util.List;
import model.A;
import model.ACriteria;
import org.apache.ibatis.annotations.Param;

public interface AMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int countByExample(ACriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int deleteByExample(ACriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int insert(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int insertSelective(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    List<A> selectByExample(ACriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    A selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") A record, @Param("example") ACriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") A record, @Param("example") ACriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(A record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table A
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(A record);
}